/*
Copyright (C) 2005-2007 Michael Keith, University Of Manchester
 
email: mkeith@pulsarastronomy.net
www  : www.pulsarastronomy.net/wiki/Software/PulsarHunter
 
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
 
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
 
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
 */
/*
 * LoadingSplash.java
 *
 * Created on 26 May 2005, 13:25
 */

package pulsarhunter.bookkeepr.jreaper;

import javax.swing.SwingUtilities;

/**
 *
 * @author  mkeith
 */
public class LoadingSplash extends javax.swing.JFrame {
    
    /** Creates new form LoadingSplash */
    public LoadingSplash() {
        initComponents();
    }
    
    public void setLoadItem(String item){
        jLabel1.setText("Loading... "+item);
        this.setTitle("Loading... "+item);
        repaint();
    }
    
    public void setText(final String text){
        Runnable task = new Runnable(){
            public void run(){
               // LoadingSplash.this.setVisible(false);
                LoadingSplash.this.setTitle(text);
                LoadingSplash.this.jLabel1.setText(text);
                LoadingSplash.this.jProgressBar1.setVisible(false);
                LoadingSplash.this.repaint();
                //LoadingSplash.this.setVisible(true);
            }
        };
        SwingUtilities.invokeLater(task);
        
        
    }
    
    public void setProgress(final String text, final int val, final int outof){
        Runnable task = new Runnable(){
            public void run(){
              //  LoadingSplash.this.setVisible(false);
                LoadingSplash.this.setTitle(text);
                LoadingSplash.this.jLabel1.setText(text);
                LoadingSplash.this.jProgressBar1.setMinimum(0);
                LoadingSplash.this.jProgressBar1.setMaximum(outof);
                LoadingSplash.this.jProgressBar1.setValue(val);
                LoadingSplash.this.jProgressBar1.setVisible(true);
                LoadingSplash.this.repaint();
             ///   LoadingSplash.this.setVisible(true);
            }
        };
        SwingUtilities.invokeLater(task);
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setFocusable(false);
        setFocusableWindowState(false);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Loading...");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jProgressBar1, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-300)/2, (screenSize.height-150)/2, 300, 150);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
}
