/*
 * DudListItemPanel.java
 *
 * Created on January 31, 2008, 1:25 PM
 */

package pulsarhunter.jreaper.gui;

import javax.swing.ListModel;

/**
 *
 * @author  mkeith
 */
public class DudListItemPanel extends javax.swing.JPanel {
    
    private String listName;
    private DataLibraryOptionsFrame master;
    
    /** Creates new form DudListItemPanel */
    public DudListItemPanel(String listName,DataLibraryOptionsFrame master,boolean enabled) {
        initComponents();
        this.listName = listName;
        this.master = master;
        this.jCheckBox1.setText(listName);
        this.jCheckBox1.setSelected(enabled);
    }
    
    public void setListEnabled(boolean enabled){
        this.jCheckBox1.setSelected(enabled);
    }
   
    public boolean isListEnabled(){
        return this.jCheckBox1.isSelected();
    }
    
    public String getListName() {
        return listName;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        setMaximumSize(new java.awt.Dimension(400, 30));
        setMinimumSize(new java.awt.Dimension(400, 30));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(400, 30));
        jCheckBox1.setText("ListName");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.setMaximumSize(new java.awt.Dimension(150, 18));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(150, 18));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(150, 18));
        add(jCheckBox1);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1);

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        add(jButton2);

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.master.editDudList(this);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.master.removeDudList(this);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
    
}
