/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pulsarhunter_BarryCenter */

#ifndef _Included_pulsarhunter_BarryCenter
#define _Included_pulsarhunter_BarryCenter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pulsarhunter_BarryCenter
 * Method:    psrephj
 * Signature: (DIDDDDDDDDDD[D)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_BarryCenter_psrephj
  (JNIEnv *, jclass cls , jdouble EPOCH, jint ITELNO, jdouble RA20,
jdouble DEC20, jdouble PBEPOCH, jdouble PB,
jdouble PBDOT, jdouble EPBIN, jdouble PBIN, jdouble ASINI, jdouble WBIN,
jdouble ECC, jdoubleArray result);

#ifdef __cplusplus
}
#endif
#endif
