#!/bin/bash
nn=$#
if=$1
of=$2
dm=$3
switches="$4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25} ${26} ${27} ${28} ${29} ${30}"

if [[ $nn -gt  30 ]]
then
echo "Can only handle 30 args... check the script ph-pdm to add more"
exit
fi


if [[ $nn -lt  4 ]]
then
echo "Please specify [datafile] [root of output] [dm] [tune params]"
cat ${PULSARHUNTER_HOME}/help/tune
exit
fi



if [ -e ${if}.sub ]
then 
echo "Assuming "$if".sub is a correct dedispersed subband timeseries"
else
echo "filterbanking and dedispersing to subbands..."
filterbank ${if}.dat | dedisperse -d $dm -b 4 -nobaseline > ${if}.sub

fi

if=${if}.sub

if [[ $nn -gt  20 ]]
then
echo "Can only handle 20 args... check the script ph-tune to add more"
exit
fi

of=`echo $of | sed 's%\.phcf%%'`


#CMD='${PULSARHUNTER_HOME}/scripts/pulsarhunter -r basictune -a "'$if' '$of'" --sw-tune="'$switches'"'

#echo $CMD

${PULSARHUNTER_HOME}/scripts/pulsarhunter -r tune -a "$if $of" --options="$switches"
exit $?
