#!/bin/bash
ARGS=$*

echo "PULSARHUNTER_HOME="${PULSARHUNTER_HOME}
source ${PULSARHUNTER_HOME}/scripts/includes/env
echo "Using java executable: "${JAVA_HOME}/bin/java


#CLASSPATH=${PULSARHUNTER_HOME}/lib/CoordLib.jar:${PULSARHUNTER_HOME}/pulsarhunter.jar:${PULSARHUNTER_HOME}/lib/swing-layout-1.0.jar:${PULSARHUNTER_HOME}/lib/AbsoluteLayout.jar

CLASSPATH=${PULSARHUNTER_HOME}/pulsarhunter.jar
for jarfile in `ls ${PULSARHUNTER_HOME}/lib/*.jar`
do
CLASSPATH=${jarfile}:${CLASSPATH}
done



#${JAVA_HOME}/bin/java -Dsystem.load.path=${PULSARHUNTER_HOME}/lib:$LD_LIBRARY_PATH -jar ${PULSARHUNTER_HOME}/pulsarhunter.jar --libpath=${PULSARHUNTER_HOME}/lib $ARGS
${JAVA_HOME}/bin/java -Xms256M -Xmx1024M -classpath $CLASSPATH pulsarhunter.PulsarHunter --libdir=${PULSARHUNTER_HOME}/lib --recdir=${PULSARHUNTER_HOME}/recipies "$1" "$2" "$3" "$4" "$5" "$6" "$7"

err=$?
if [[ $err == 1 ]]
then
   echo
   echo "Wrong Version of Java appears to be in use..."
   echo "Please use Java 1.5 or above"
fi
exit $err
