/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pulsarhunter_PgplotInterface */

#ifndef _Included_pulsarhunter_PgplotInterface
#define _Included_pulsarhunter_PgplotInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pgopen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgopen
  (JNIEnv *env, jclass cl, jstring device);

/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pgclose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgclose
  (JNIEnv *env, jclass cl);

/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pgsvp
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgsvp
  (JNIEnv *env, jclass cl, jfloat xleft, jfloat xright, jfloat ybot, jfloat ytop);

/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pgswin
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgswin
  (JNIEnv *env, jclass cl,  jfloat xleft, jfloat xright, jfloat ybot, jfloat ytop);

/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pgqwin
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgqwin
  (JNIEnv *env, jclass cl, jfloatArray retVal);

/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pgmove
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgmove
  (JNIEnv *env, jclass cl, jfloat x, jfloat y);

/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pgdraw
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgdraw
  (JNIEnv *env, jclass cl, jfloat x, jfloat y);

JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgsch
(JNIEnv *env, jclass cl, jfloat x);


/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pglab
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pglab
  (JNIEnv *env, jclass cl, jstring x, jstring y, jstring top);

/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pggray
 * Signature: ([FIIIIIIFFF)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pggray
  (JNIEnv *env, jclass cl, jfloatArray arr, jint idim, jint jdim, jint i1, jint i2, jint j1, jint j2, jfloat fg, jfloat bg, jfloatArray tr);

/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    pgbox
 * Signature: (Ljava/lang/String;FFLjava/lang/String;FI)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgbox
  (JNIEnv *env, jclass cl, jstring xopt, jfloat xtic, jint nxsub , jstring yopt, jfloat ytic, jint nysub);

JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_pgtext
(JNIEnv *env, jclass cl, jstring text, jfloat x, jfloat y);


/*
 * Class:     pulsarhunter_PgplotInterface
 * Method:    quikgray
 * Signature: ([FIII)V
 */
JNIEXPORT void JNICALL Java_pulsarhunter_PgplotInterface_quikgray
  (JNIEnv *env, jclass cl, jfloatArray dat, jint nx, jint ny, jint nxx);

void MKtestMe();

#ifdef __cplusplus
}
#endif
#endif
