/*
Copyright (C) 2005-2007 Michael Keith, University Of Manchester

email: mkeith@pulsarastronomy.net
www  : www.pulsarastronomy.net/wiki/Software/PulsarHunter

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

*/
/*
 * PDMFrame.java
 *
 * Created on 27 May 2005, 16:33
 */

package pulsarhunter.jreaper.pmsurv;


import ptolemy.plot.Render;
import pulsarhunter.jreaper.Cand;




/**
 *
 * @author  mkeith
 */
public class PDMFrame extends Render {
    Thread thread;
    /** Creates new form PDMFrame */
    public PDMFrame(final PulsarCandFile phfile,final Cand cand) {
        this(phfile,cand,true);
    }
    public PDMFrame(final PulsarCandFile phfile,final Cand cand,boolean threads) {
        initComponents();
        if(threads){
            thread = new Thread(){
                public void run(){
                    PDMFrame.this.setup(phfile,cand);
                }
            };
            thread.start();
            
        } else {
            setup(phfile,cand);
        }
    }
    
    private void setup(final PulsarCandFile phfile,final Cand cand){
        
        final int[][] colourarray = phfile.getPDMprof(255);
        
        
        // Create a sample plot.
        
        clear(true);
        setGrid(false);
        int nbin = phfile.getNbin();
        setColormap(cand.getCandList().getDataLibrary().getOptions().getGrayColourMap().getGCols());
        setTitle("PDM plot");
        //setYLabel("DM");
        //setXLabel("Period");
        setXIncrement(1.0);
        //setXOffset(-(colourarray.length)/2);
        setYIncrement(1.0);
        //setYOffset(-(colourarray[0].length)/2);
        
        // Create the stripes in data form (arrays).
        
        
        
        
        // Reset the data structure.
        clearData();
        
        // Add the stripes to the data structure.
        for (int i = 0; i<colourarray.length; i++) {
            addStripe(colourarray[i]);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PDMFrame.this.repaint();
            }
        });
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setLayout(new java.awt.BorderLayout());
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
