/*
Copyright (C) 2005-2007 Michael Keith, University Of Manchester

email: mkeith@pulsarastronomy.net
www  : www.pulsarastronomy.net/wiki/Software/PulsarHunter

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

*/
/*
 * subintPanel.java
 *
 * Created on 24 May 2005, 17:57
 */

package pulsarhunter.jreaper.pmsurv;

import java.awt.Point;
import ptolemy.plot.Render;
import pulsarhunter.jreaper.Cand;




/**
 *
 * @author  mkeith
 */
public class SubintPanel extends Render {
    Thread thread;
    public SubintPanel(){}
    /** Creates new form subintPanel */
    public SubintPanel(final PulsarCandFile phfile,final Cand cand,final double phase,int reqSubInts) {
     this(phfile,cand,phase,reqSubInts,true);
    }
    
    public SubintPanel(final PulsarCandFile phfile,final Cand cand,final double phase,final int reqSubInts,boolean threads) {
        initComponents();
        
        if(threads){
            
            thread = new Thread(){
                public void run(){
                    // Create a sample plot.
                    SubintPanel.this.setup(phfile,cand,phase,reqSubInts);
                    
                }};
                thread.start();
        } else {
            setup(phfile,cand,phase,reqSubInts);
        }
    }
    
    private void setup(final PulsarCandFile phfile,final Cand cand,double phase,int reqSubInts){
        final int[][] colourarray = phfile.getSubints(255,phase,reqSubInts);
        clear(true);
        setGrid(false);
        int nbin = phfile.getNbin();
        setColormap(cand.getCandList().getDataLibrary().getOptions().getGrayColourMap().getGCols());
        setTitle("Subintegrations");
        setYLabel("Subint");
        setXLabel("Phase");
        setXIncrement(1.0/nbin);
        setXOffset(0.0);
        setYIncrement(1);
        setYOffset(0.0);
        
        // Create the stripes in data form (arrays).
        
        
        
        
        // Reset the data structure.
        clearData();
        
        // Add the stripes to the data structure.
        for (int i = 0; i<colourarray.length; i++) {
            addStripe(colourarray[i]);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SubintPanel.this.repaint();
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickhandler(evt);
            }
        });

    }//GEN-END:initComponents
    
    private void clickhandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickhandler
        
        if(evt.getButton()==evt.BUTTON3){
            Point p = evt.getPoint();
            System.out.println(p.getX());
            System.out.println(p.getY());
        }
    }//GEN-LAST:event_clickhandler
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
